### ISSUE TITLE
update() not working

### ISSUE THREAD

**Issue by AMMullan** [rbw0/python-servicenow-rest#3]
I've been working on moving to REST and going by the official documentation they say to use POST for new tickets and PUT for updates but your script seems to have it the other way around...?

Also, 2 issues specific to your POST queries as is:
* You pass a query but I'm not sure what this query is meant to be? From the testing I did using REST prior to using your library you don't pass any other sysparms?
* The sysid that is being passed isn't actually being used - On line 109, you check for it's existence but then you use self.sysid which never gets used.

Are these known issues or am I just not using it correctly?

**Comment by rbw0** [comment]
This has been fixed. You can get the latest version from pypi.

Thanks for reporting.

**Comment by rbw0** [comment]
a343003
